### ISSUE TITLE
additionalProperty check in validation

### ISSUE THREAD

**Issue by thepriestscottage** [hes-pnnl/hes-validation-engine#50]
The additionalProperty errors are not being returned in our validation engine.  Example:
```
'{"apples" : "3"}'
> missing values caught, but missing expected { additionalProperty: 'apples' } error
```

We need to handle for these, and also check for others possible like this.

**Comment by BenjaminStuermer** [comment]
This is fixed here: https://github.com/hes-pnnl/hes-validation-engine/commit/a371ed3667d816e172db26a5532e570783cf7f52. I implemented this in the typescript branch since merging changes into that branch would be obnoxious.
